day_limit:
  tag_attributes:
    type: number
  category: Reservation Settings
max_concurrent_reservations:
  tag_attributes:
    type: number
  category: Reservation Settings
reservation_email:
  tag_attributes:
    class: tinymce
  field_type: text_area
  category: Email Settings
from_name:
  category: Email Settings
from_address:
  category: Email Settings